"""empty message

Revision ID: 59f3082483dd
Revises: ca9eec44e3f1
Create Date: 2019-09-21 15:52:11.556530

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '59f3082483dd'
down_revision = 'ca9eec44e3f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'twitch_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('twitch_id', sa.VARCHAR(length=128), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
