"""empty message

Revision ID: 763fc9f85cf2
Revises: 59f3082483dd
Create Date: 2019-09-21 17:15:08.386984

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '763fc9f85cf2'
down_revision = '59f3082483dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('twitch_id', sa.String(length=120), nullable=False, server_default=''))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'twitch_id')
    # ### end Alembic commands ###
