"""empty message

Revision ID: ca9eec44e3f1
Revises: 875e320523d6
Create Date: 2019-09-21 15:42:34.689405

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ca9eec44e3f1'
down_revision = '875e320523d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oauth',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('token', sqlalchemy_utils.types.json.JSONType(), nullable=False),
    sa.Column('provider_user_id', sa.String(length=256), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_user_id')
    )
    op.add_column('user', sa.Column('twitch_id', sa.String(length=128), nullable=False))
    op.drop_column('user', 'provider')
    op.drop_column('user', 'created_at')
    op.drop_column('user', 'token')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('token', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('provider', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_column('user', 'twitch_id')
    op.drop_table('oauth')
    # ### end Alembic commands ###
